databaseChangeLog:
  - changeSet:
      id: create-and-init-roles-table
      author: riki
      changes:
        - createTable:
            tableName: roles
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: varchar(255)
                  constraints:
                    nullable: false
                    unique: true
        - insert:
            tableName: roles
            columns:
              - column:
                  name: name
                  value: "ROLE_USER"
        - insert:
            tableName: roles
            columns:
              - column:
                  name: name
                  value: "ROLE_ADMIN"
